[sergio]
a = [1,2,3]
[sergio.arturo.garcia.camargo]
b = "sergio"
[sergio.arturo]
b = 1
[[sergio.checho]]
b = 2
[[sergio.checho.angulo]]
b = 2
[[sergio.checho]]
b = 2
[[sergio.checho.angulo]]
b = 2
[[sergio.checho]]
b = 2
[[sergio.checho.angulo]]
b = 2


